// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaHt-jiEHNnb4A0RgdSZYhsTi57UDx9Jg',
    appId: '1:456723411643:web:8fe376a7092fce4206af9e',
    messagingSenderId: '456723411643',
    projectId: 'lostfoundapp-1111',
    authDomain: 'lostfoundapp-1111.firebaseapp.com',
    storageBucket: 'lostfoundapp-1111.firebasestorage.app',
    measurementId: 'G-Y2G7BHW6V3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDadjzuoIkPJx-9RVCj9V2YKH5r7LGx09Q',
    appId: '1:456723411643:android:413df5f753a65ef606af9e',
    messagingSenderId: '456723411643',
    projectId: 'lostfoundapp-1111',
    storageBucket: 'lostfoundapp-1111.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYkwNQv4afw5yL2jMajQ6CK8sRt_AdEvs',
    appId: '1:456723411643:ios:f5fb920ec9f3761f06af9e',
    messagingSenderId: '456723411643',
    projectId: 'lostfoundapp-1111',
    storageBucket: 'lostfoundapp-1111.firebasestorage.app',
    iosBundleId: 'com.example.lostAndFoundapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYkwNQv4afw5yL2jMajQ6CK8sRt_AdEvs',
    appId: '1:456723411643:ios:7b46357f5decc56d06af9e',
    messagingSenderId: '456723411643',
    projectId: 'lostfoundapp-1111',
    storageBucket: 'lostfoundapp-1111.firebasestorage.app',
    iosBundleId: 'com.example.lostAndFound',
  );

}