// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5kd63PexFN6MGCbcNhObj57BMTUK49zA',
    appId: '1:600279841348:web:8d2136ff6c096a986f9a11',
    messagingSenderId: '600279841348',
    projectId: 'lostfoundapp-1e774',
    authDomain: 'lostfoundapp-1e774.firebaseapp.com',
    storageBucket: 'lostfoundapp-1e774.appspot.com',
    measurementId: 'G-DMQGESVBC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQnNhxrREtRx9H7VqoH6QdLnoK9-cAS1s',
    appId: '1:600279841348:android:fa51f5c34eda406b6f9a11',
    messagingSenderId: '600279841348',
    projectId: 'lostfoundapp-1e774',
    storageBucket: 'lostfoundapp-1e774.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdyozC9un9AexKzlwuHlewnL6tHIZdrC4',
    appId: '1:600279841348:ios:af8aa7f4db89edde6f9a11',
    messagingSenderId: '600279841348',
    projectId: 'lostfoundapp-1e774',
    storageBucket: 'lostfoundapp-1e774.appspot.com',
    iosBundleId: 'com.example.lostAndFound',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdyozC9un9AexKzlwuHlewnL6tHIZdrC4',
    appId: '1:600279841348:ios:d881404e584681a26f9a11',
    messagingSenderId: '600279841348',
    projectId: 'lostfoundapp-1e774',
    storageBucket: 'lostfoundapp-1e774.appspot.com',
    iosBundleId: 'com.example.lostAndFound.RunnerTests',
  );
}
